// ====================================================================
//  ПЕРЕВОДЫ НА 10 ЯЗЫКОВ (ПОЛНАЯ ВЕРСИЯ)
// ====================================================================
const translations = {
    ru: {
        login: 'Вход',
        register: 'Регистрация',
        email: 'Email',
        password: 'Пароль',
        remember: 'Запомнить меня',
        forgot: 'Забыли пароль?',
        loginBtn: 'Войти',
        registerBtn: 'Зарегистрироваться',
        noAccount: 'Нет аккаунта?',
        hasAccount: 'Уже есть аккаунт?',
        profile: '👤 Профиль',
        logout: '🚪 Выйти',
        backToMain: '← Вернуться на главную',
        entries: 'Записей',
        favorites: 'Избранное',
        days: 'Дней',
        memberSince: 'Зарегистрирован',
        editProfile: '✏️ Редактировать профиль',
        save: '💾 Сохранить',
        cancel: 'Отмена',
        fullName: 'Полное имя',
        username: 'Имя пользователя',
        bio: 'О себе',
        changePassword: '🔒 Сменить пароль',
        currentPassword: 'Текущий пароль',
        newPassword: 'Новый пароль (мин. 6 символов)',
        confirmPassword: 'Подтвердите новый пароль',
        savePassword: '💾 Сменить пароль',
        favoritesTitle: '⭐ Избранное',
        noFavorites: '📭 У вас пока нет избранного',
        addToFavorites: '⭐ В избранное',
        removeFromFavorites: '🗑️ Удалить',
        addedToFavorites: '⭐ Добавлено в избранное!',
        removedFromFavorites: '🗑️ Удалено из избранного',
        alreadyInFavorites: '⚠️ Уже в избранном!',
        resetTitle: '🔐 Восстановление пароля',
        resetSubtitle: 'Введите email, мы отправим ссылку для сброса',
        resetEmail: 'Email',
        resetSend: 'Отправить ссылку',
        backToLogin: '← Назад ко входу',
        resetSuccess: '✅ Ссылка отправлена на вашу почту!',
        customize: 'Настройка цветов',
        settings: 'Настройка цветов',
        bgColor: 'Цвет фона:',
        glassColor: 'Цвет стекла (блок):',
        glassOpacity: 'Прозрачность стекла:',
        resetColors: 'Сбросить цвета'
    },
    en: {
        login: 'Login',
        register: 'Sign Up',
        email: 'Email',
        password: 'Password',
        remember: 'Remember me',
        forgot: 'Forgot password?',
        loginBtn: 'Login',
        registerBtn: 'Sign Up',
        noAccount: "Don't have an account?",
        hasAccount: 'Already have an account?',
        profile: '👤 Profile',
        logout: '🚪 Logout',
        backToMain: '← Back to Main',
        entries: 'Entries',
        favorites: 'Favorites',
        days: 'Days',
        memberSince: 'Member since',
        editProfile: '✏️ Edit Profile',
        save: '💾 Save',
        cancel: 'Cancel',
        fullName: 'Full Name',
        username: 'Username',
        bio: 'Bio',
        changePassword: '🔒 Change Password',
        currentPassword: 'Current Password',
        newPassword: 'New Password (min. 6 characters)',
        confirmPassword: 'Confirm New Password',
        savePassword: '💾 Change Password',
        favoritesTitle: '⭐ Favorites',
        noFavorites: '📭 No favorites yet',
        addToFavorites: '⭐ Add to favorites',
        removeFromFavorites: '🗑️ Remove',
        addedToFavorites: '⭐ Added to favorites!',
        removedFromFavorites: '🗑️ Removed from favorites',
        alreadyInFavorites: '⚠️ Already in favorites!',
        resetTitle: '🔐 Reset Password',
        resetSubtitle: 'Enter your email to reset password',
        resetEmail: 'Email',
        resetSend: 'Send reset link',
        backToLogin: '← Back to Login',
        resetSuccess: '✅ Reset link sent to your email!',
        customize: 'Customize Colors',
        settings: 'Color Settings',
        bgColor: 'Background Color:',
        glassColor: 'Glass Color (Block):',
        glassOpacity: 'Glass Opacity:',
        resetColors: 'Reset Colors'
    },
    es: {
        login: 'Iniciar Sesión',
        register: 'Registrarse',
        email: 'Correo electrónico',
        password: 'Contraseña',
        remember: 'Recordarme',
        forgot: '¿Olvidaste tu contraseña?',
        loginBtn: 'Iniciar Sesión',
        registerBtn: 'Registrarse',
        noAccount: '¿No tienes cuenta?',
        hasAccount: '¿Ya tienes cuenta?',
        profile: '👤 Perfil',
        logout: '🚪 Cerrar Sesión',
        backToMain: '← Volver al inicio',
        entries: 'Entradas',
        favorites: 'Favoritos',
        days: 'Días',
        memberSince: 'Miembro desde',
        editProfile: '✏️ Editar Perfil',
        save: '💾 Guardar',
        cancel: 'Cancelar',
        fullName: 'Nombre completo',
        username: 'Nombre de usuario',
        bio: 'Sobre mí',
        changePassword: '🔒 Cambiar Contraseña',
        currentPassword: 'Contraseña actual',
        newPassword: 'Nueva contraseña (mín. 6 caracteres)',
        confirmPassword: 'Confirmar nueva contraseña',
        savePassword: '💾 Cambiar Contraseña',
        favoritesTitle: '⭐ Favoritos',
        noFavorites: '📭 No tienes favoritos',
        addToFavorites: '⭐ Añadir a favoritos',
        removeFromFavorites: '🗑️ Eliminar',
        addedToFavorites: '⭐ ¡Añadido a favoritos!',
        removedFromFavorites: '🗑️ Eliminado de favoritos',
        alreadyInFavorites: '⚠️ ¡Ya está en favoritos!',
        resetTitle: '🔐 Restablecer Contraseña',
        resetSubtitle: 'Ingresa tu correo para restablecer contraseña',
        resetEmail: 'Correo electrónico',
        resetSend: 'Enviar enlace',
        backToLogin: '← Volver al inicio de sesión',
        resetSuccess: '✅ ¡Enlace enviado a tu correo!',
        customize: 'Personalizar Colores',
        settings: 'Configuración de Colores',
        bgColor: 'Color de fondo:',
        glassColor: 'Color del vidrio (bloque):',
        glassOpacity: 'Opacidad del vidrio:',
        resetColors: 'Restablecer Colores'
    },
    fr: {
        login: 'Se Connecter',
        register: "S'inscrire",
        email: 'Email',
        password: 'Mot de passe',
        remember: 'Se souvenir de moi',
        forgot: 'Mot de passe oublié?',
        loginBtn: 'Se Connecter',
        registerBtn: "S'inscrire",
        noAccount: "Pas de compte?",
        hasAccount: 'Déjà un compte?',
        profile: '👤 Profil',
        logout: '🚪 Se Déconnecter',
        backToMain: '← Retour à l\'accueil',
        entries: 'Entrées',
        favorites: 'Favoris',
        days: 'Jours',
        memberSince: 'Membre depuis',
        editProfile: '✏️ Modifier le profil',
        save: '💾 Enregistrer',
        cancel: 'Annuler',
        fullName: 'Nom complet',
        username: "Nom d'utilisateur",
        bio: 'Bio',
        changePassword: '🔒 Changer le mot de passe',
        currentPassword: 'Mot de passe actuel',
        newPassword: 'Nouveau mot de passe (min. 6 caractères)',
        confirmPassword: 'Confirmer le nouveau mot de passe',
        savePassword: '💾 Changer le mot de passe',
        favoritesTitle: '⭐ Favoris',
        noFavorites: '📭 Pas de favoris',
        addToFavorites: '⭐ Ajouter aux favoris',
        removeFromFavorites: '🗑️ Supprimer',
        addedToFavorites: '⭐ Ajouté aux favoris!',
        removedFromFavorites: '🗑️ Supprimé des favoris',
        alreadyInFavorites: '⚠️ Déjà dans les favoris!',
        resetTitle: '🔐 Réinitialiser le mot de passe',
        resetSubtitle: 'Entrez votre email pour réinitialiser',
        resetEmail: 'Email',
        resetSend: 'Envoyer le lien',
        backToLogin: '← Retour à la connexion',
        resetSuccess: '✅ Lien envoyé à votre email!',
        customize: 'Personnaliser les couleurs',
        settings: 'Paramètres de couleurs',
        bgColor: 'Couleur de fond:',
        glassColor: 'Couleur du verre (bloc):',
        glassOpacity: 'Opacité du verre:',
        resetColors: 'Réinitialiser les couleurs'
    },
    de: {
        login: 'Anmelden',
        register: 'Registrieren',
        email: 'E-Mail',
        password: 'Passwort',
        remember: 'Angemeldet bleiben',
        forgot: 'Passwort vergessen?',
        loginBtn: 'Anmelden',
        registerBtn: 'Registrieren',
        noAccount: 'Kein Konto?',
        hasAccount: 'Bereits ein Konto?',
        profile: '👤 Profil',
        logout: '🚪 Abmelden',
        backToMain: '← Zurück zur Startseite',
        entries: 'Einträge',
        favorites: 'Favoriten',
        days: 'Tage',
        memberSince: 'Mitglied seit',
        editProfile: '✏️ Profil bearbeiten',
        save: '💾 Speichern',
        cancel: 'Abbrechen',
        fullName: 'Vollständiger Name',
        username: 'Benutzername',
        bio: 'Über mich',
        changePassword: '🔒 Passwort ändern',
        currentPassword: 'Aktuelles Passwort',
        newPassword: 'Neues Passwort (min. 6 Zeichen)',
        confirmPassword: 'Neues Passwort bestätigen',
        savePassword: '💾 Passwort ändern',
        favoritesTitle: '⭐ Favoriten',
        noFavorites: '📭 Keine Favoriten',
        addToFavorites: '⭐ Zu Favoriten hinzufügen',
        removeFromFavorites: '🗑️ Entfernen',
        addedToFavorites: '⭐ Zu Favoriten hinzugefügt!',
        removedFromFavorites: '🗑️ Aus Favoriten entfernt',
        alreadyInFavorites: '⚠️ Bereits in Favoriten!',
        resetTitle: '🔐 Passwort zurücksetzen',
        resetSubtitle: 'Geben Sie Ihre E-Mail ein',
        resetEmail: 'E-Mail',
        resetSend: 'Link senden',
        backToLogin: '← Zurück zum Login',
        resetSuccess: '✅ Link wurde an Ihre E-Mail gesendet!',
        customize: 'Farben anpassen',
        settings: 'Farbeinstellungen',
        bgColor: 'Hintergrundfarbe:',
        glassColor: 'Glasfarbe (Block):',
        glassOpacity: 'Glasdeckkraft:',
        resetColors: 'Farben zurücksetzen'
    },
    pt: {
        login: 'Entrar',
        register: 'Registrar',
        email: 'E-mail',
        password: 'Senha',
        remember: 'Lembrar-me',
        forgot: 'Esqueceu a senha?',
        loginBtn: 'Entrar',
        registerBtn: 'Registrar',
        noAccount: 'Não tem conta?',
        hasAccount: 'Já tem conta?',
        profile: '👤 Perfil',
        logout: '🚪 Sair',
        backToMain: '← Voltar ao início',
        entries: 'Entradas',
        favorites: 'Favoritos',
        days: 'Dias',
        memberSince: 'Membro desde',
        editProfile: '✏️ Editar Perfil',
        save: '💾 Salvar',
        cancel: 'Cancelar',
        fullName: 'Nome completo',
        username: 'Nome de usuário',
        bio: 'Sobre mim',
        changePassword: '🔒 Alterar Senha',
        currentPassword: 'Senha atual',
        newPassword: 'Nova senha (mín. 6 caracteres)',
        confirmPassword: 'Confirmar nova senha',
        savePassword: '💾 Alterar Senha',
        favoritesTitle: '⭐ Favoritos',
        noFavorites: '📭 Sem favoritos',
        addToFavorites: '⭐ Adicionar aos favoritos',
        removeFromFavorites: '🗑️ Remover',
        addedToFavorites: '⭐ Adicionado aos favoritos!',
        removedFromFavorites: '🗑️ Removido dos favoritos',
        alreadyInFavorites: '⚠️ Já está nos favoritos!',
        resetTitle: '🔐 Redefinir Senha',
        resetSubtitle: 'Digite seu email para redefinir',
        resetEmail: 'E-mail',
        resetSend: 'Enviar link',
        backToLogin: '← Voltar ao login',
        resetSuccess: '✅ Link enviado para seu e-mail!',
        customize: 'Personalizar Cores',
        settings: 'Configurações de Cores',
        bgColor: 'Cor de fundo:',
        glassColor: 'Cor do vidro (bloco):',
        glassOpacity: 'Opacidade do vidro:',
        resetColors: 'Redefinir Cores'
    },
    it: {
        login: 'Accedi',
        register: 'Registrati',
        email: 'Email',
        password: 'Password',
        remember: 'Ricordami',
        forgot: 'Password dimenticata?',
        loginBtn: 'Accedi',
        registerBtn: 'Registrati',
        noAccount: 'Non hai un account?',
        hasAccount: 'Hai già un account?',
        profile: '👤 Profilo',
        logout: '🚪 Esci',
        backToMain: '← Torna alla home',
        entries: 'Voci',
        favorites: 'Preferiti',
        days: 'Giorni',
        memberSince: 'Membro dal',
        editProfile: '✏️ Modifica Profilo',
        save: '💾 Salva',
        cancel: 'Annulla',
        fullName: 'Nome completo',
        username: 'Nome utente',
        bio: 'Bio',
        changePassword: '🔒 Cambia Password',
        currentPassword: 'Password attuale',
        newPassword: 'Nuova password (min. 6 caratteri)',
        confirmPassword: 'Conferma nuova password',
        savePassword: '💾 Cambia Password',
        favoritesTitle: '⭐ Preferiti',
        noFavorites: '📭 Nessun preferito',
        addToFavorites: '⭐ Aggiungi ai preferiti',
        removeFromFavorites: '🗑️ Rimuovi',
        addedToFavorites: '⭐ Aggiunto ai preferiti!',
        removedFromFavorites: '🗑️ Rimosso dai preferiti',
        alreadyInFavorites: '⚠️ Già nei preferiti!',
        resetTitle: '🔐 Reimposta Password',
        resetSubtitle: 'Inserisci la tua email',
        resetEmail: 'Email',
        resetSend: 'Invia link',
        backToLogin: '← Torna al login',
        resetSuccess: '✅ Link inviato alla tua email!',
        customize: 'Personalizza Colori',
        settings: 'Impostazioni Colori',
        bgColor: 'Colore sfondo:',
        glassColor: 'Colore vetro (blocco):',
        glassOpacity: 'Opacità vetro:',
        resetColors: 'Reimposta Colori'
    },
    ja: {
        login: 'ログイン',
        register: '登録',
        email: 'メールアドレス',
        password: 'パスワード',
        remember: 'ログイン状態を保持',
        forgot: 'パスワードをお忘れですか？',
        loginBtn: 'ログイン',
        registerBtn: '登録',
        noAccount: 'アカウントをお持ちでない方',
        hasAccount: 'すでにアカウントをお持ちの方',
        profile: '👤 プロフィール',
        logout: '🚪 ログアウト',
        backToMain: '← ホームに戻る',
        entries: 'エントリー',
        favorites: 'お気に入り',
        days: '日数',
        memberSince: '登録日',
        editProfile: '✏️ プロフィール編集',
        save: '💾 保存',
        cancel: 'キャンセル',
        fullName: 'フルネーム',
        username: 'ユーザー名',
        bio: '自己紹介',
        changePassword: '🔒 パスワード変更',
        currentPassword: '現在のパスワード',
        newPassword: '新しいパスワード（6文字以上）',
        confirmPassword: '新しいパスワード（確認）',
        savePassword: '💾 パスワード変更',
        favoritesTitle: '⭐ お気に入り',
        noFavorites: '📭 お気に入りはありません',
        addToFavorites: '⭐ お気に入りに追加',
        removeFromFavorites: '🗑️ 削除',
        addedToFavorites: '⭐ お気に入りに追加しました！',
        removedFromFavorites: '🗑️ お気に入りから削除しました',
        alreadyInFavorites: '⚠️ すでにお気に入りです！',
        resetTitle: '🔐 パスワードをリセット',
        resetSubtitle: 'メールアドレスを入力してください',
        resetEmail: 'メールアドレス',
        resetSend: 'リンクを送信',
        backToLogin: '← ログインに戻る',
        resetSuccess: '✅ リセットリンクを送信しました！',
        customize: 'カラーをカスタマイズ',
        settings: 'カラー設定',
        bgColor: '背景色:',
        glassColor: 'ガラスの色（ブロック）:',
        glassOpacity: 'ガラスの透明度:',
        resetColors: '色をリセット'
    },
    zh: {
        login: '登录',
        register: '注册',
        email: '电子邮箱',
        password: '密码',
        remember: '记住我',
        forgot: '忘记密码？',
        loginBtn: '登录',
        registerBtn: '注册',
        noAccount: '没有账号？',
        hasAccount: '已有账号？',
        profile: '👤 个人资料',
        logout: '🚪 退出',
        backToMain: '← 返回首页',
        entries: '条目',
        favorites: '收藏',
        days: '天数',
        memberSince: '注册于',
        editProfile: '✏️ 编辑资料',
        save: '💾 保存',
        cancel: '取消',
        fullName: '全名',
        username: '用户名',
        bio: '个人简介',
        changePassword: '🔒 修改密码',
        currentPassword: '当前密码',
        newPassword: '新密码（至少6位）',
        confirmPassword: '确认新密码',
        savePassword: '💾 修改密码',
        favoritesTitle: '⭐ 收藏',
        noFavorites: '📭 暂无收藏',
        addToFavorites: '⭐ 添加收藏',
        removeFromFavorites: '🗑️ 删除',
        addedToFavorites: '⭐ 已添加收藏！',
        removedFromFavorites: '🗑️ 已删除收藏',
        alreadyInFavorites: '⚠️ 已收藏！',
        resetTitle: '🔐 重置密码',
        resetSubtitle: '请输入您的电子邮箱',
        resetEmail: '电子邮箱',
        resetSend: '发送链接',
        backToLogin: '← 返回登录',
        resetSuccess: '✅ 重置链接已发送！',
        customize: '自定义颜色',
        settings: '颜色设置',
        bgColor: '背景颜色:',
        glassColor: '玻璃颜色（块）:',
        glassOpacity: '玻璃透明度:',
        resetColors: '重置颜色'
    },
    ar: {
        login: 'تسجيل الدخول',
        register: 'إنشاء حساب',
        email: 'البريد الإلكتروني',
        password: 'كلمة المرور',
        remember: 'تذكرني',
        forgot: 'نسيت كلمة المرور؟',
        loginBtn: 'تسجيل الدخول',
        registerBtn: 'إنشاء حساب',
        noAccount: 'ليس لديك حساب؟',
        hasAccount: 'لديك حساب بالفعل؟',
        profile: '👤 الملف الشخصي',
        logout: '🚪 تسجيل الخروج',
        backToMain: '← العودة إلى الرئيسية',
        entries: 'المدخلات',
        favorites: 'المفضلة',
        days: 'أيام',
        memberSince: 'عضو منذ',
        editProfile: '✏️ تعديل الملف الشخصي',
        save: '💾 حفظ',
        cancel: 'إلغاء',
        fullName: 'الاسم الكامل',
        username: 'اسم المستخدم',
        bio: 'نبذة عني',
        changePassword: '🔒 تغيير كلمة المرور',
        currentPassword: 'كلمة المرور الحالية',
        newPassword: 'كلمة مرور جديدة (6 أحرف على الأقل)',
        confirmPassword: 'تأكيد كلمة المرور الجديدة',
        savePassword: '💾 تغيير كلمة المرور',
        favoritesTitle: '⭐ المفضلة',
        noFavorites: '📭 لا توجد مفضلة',
        addToFavorites: '⭐ إضافة إلى المفضلة',
        removeFromFavorites: '🗑️ إزالة',
        addedToFavorites: '⭐ تمت الإضافة إلى المفضلة!',
        removedFromFavorites: '🗑️ تمت الإزالة من المفضلة',
        alreadyInFavorites: '⚠️ موجود بالفعل في المفضلة!',
        resetTitle: '🔐 إعادة تعيين كلمة المرور',
        resetSubtitle: 'أدخل بريدك الإلكتروني',
        resetEmail: 'البريد الإلكتروني',
        resetSend: 'إرسال الرابط',
        backToLogin: '← العودة إلى تسجيل الدخول',
        resetSuccess: '✅ تم إرسال رابط إعادة التعيين!',
        customize: 'تخصيص الألوان',
        settings: 'إعدادات الألوان',
        bgColor: 'لون الخلفية:',
        glassColor: 'لون الزجاج (الكتلة):',
        glassOpacity: 'شفافية الزجاج:',
        resetColors: 'إعادة تعيين الألوان'
    }
};

// ====================================================================
//  ТЕКУЩИЙ ЯЗЫК
// ====================================================================
let currentLang = localStorage.getItem('lang') || 'ru';

// ====================================================================
//  ПЕРЕКЛЮЧЕНИЕ ЯЗЫКА (ПО КРУГУ, ПО ВСЕМ ЯЗЫКАМ)
// ====================================================================
window.toggleLang = function () {
    const langCodes = Object.keys(translations);
    const currentIndex = langCodes.indexOf(currentLang);
    const nextIndex = (currentIndex + 1) % langCodes.length;
    currentLang = langCodes[nextIndex];
    localStorage.setItem('lang', currentLang);
    updateLanguage();
};

// ====================================================================
//  ОБНОВЛЕНИЕ ЯЗЫКА НА СТРАНИЦЕ
// ====================================================================
function updateLanguage() {
    const t = translations[currentLang];
    if (!t) return;

    document.querySelectorAll('[data-i18n]').forEach(el => {
        const key = el.getAttribute('data-i18n');
        if (t[key] !== undefined) {
            if (el.tagName === 'INPUT' && el.hasAttribute('placeholder')) {
                el.placeholder = t[key];
            } else {
                el.textContent = t[key];
            }
        }
    });

    const langBtn = document.getElementById('langToggle');
    if (langBtn) {
        langBtn.textContent = currentLang.toUpperCase();
    }
}

// ====================================================================
//  ИНИЦИАЛИЗАЦИЯ
// ====================================================================
document.addEventListener('DOMContentLoaded', function () {
    currentLang = localStorage.getItem('lang') || 'ru';
    updateLanguage();
    
    const langBtn = document.getElementById('langToggle');
    if (langBtn) {
        langBtn.replaceWith(langBtn.cloneNode(true));
        document.getElementById('langToggle').addEventListener('click', function (e) {
            e.preventDefault();
            toggleLang();
        });
    }
});

console.log('✅ lang.js загружен');